In [6]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from scipy import stats
data=pd.read_csv('D:/Data Analysis/good_reads_final.csv')
df = pd.DataFrame(data)
min_max=MinMaxScaler()
print("min-max normalisation")
print("Normalised data of author_average_rating")
print(min_max.fit_transform(df[['author_average_rating']]))
print("Normalised data of book_average_rating")
print(min_max.fit_transform(df[['book_average_rating']]))
print("Normalised data of score")
print(min_max.fit_transform(df[['score']]))


print("Z-Score normalisation")
print("Normalised data of author_average_rating")
a=np.array(df['author_average_rating'])
print(stats.zscore(a))
print("book_average_rating")
b=np.array(df['book_average_rating'])
print(stats.zscore(b))
print("Normalised data of score")
c=np.array(df['score'])
print(stats.zscore(c))

min-max normalisation
Normalised data of author_average_rating
[[0.68867925]
 [0.7327044 ]
 [0.68553459]
 ...
 [0.68553459]
 [0.74842767]
 [0.70754717]]
Normalised data of book_average_rating
[[0.804]
 [0.826]
 [0.798]
 ...
 [0.746]
 [0.778]
 [0.914]]
Normalised data of score
[[0.00530746]
 [0.00502662]
 [0.00757253]
 ...
 [0.00271474]
 [0.00307916]
 [0.00534089]]
Z-Score normalisation
Normalised data of author_average_rating
[0.20644115 0.7887654  0.16484656 ... 0.16484656 0.99673834 0.45600869]
book_average_rating
[ 0.23529485  0.61289822  0.13231211 ... -0.76020494 -0.21096368
  2.1233117 ]
Normalised data of score
[-0.06015622 -0.07539877  0.06278221 ... -0.20087762 -0.1810986
 -0.05834163]


C:\Users\mukes\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:323: DataConversionWarning: Data with input dtype int64 were all converted to float64 by MinMaxScaler.
  return self.partial_fit(X, y)
